# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/flynsarmy/menu/models/menu/columns.yaml

# Model Class name
modelClass: Flynsarmy\Menu\Models\Menu

# List Title
title: Manage Menus

# Link URL for each record
recordUrl: flynsarmy/menu/menus/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Display checkboxes next to each record
showCheckboxes: false

showTree: false

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
